### ISSUE TITLE
Forget password functionality

### ISSUE THREAD

**Issue by Codeindeed** [dscfuto-org/fasthrash-FE#19]
Create a function that send arequest for forgetting password or resetting password and an alert that says message sent

**Comment by ankitraj10** [comment]
Hi @Codeindeed  ,Can you please describe about request link to be called on forget password /resetting password click?

**Comment by Codeindeed** [comment]
ok it should be on the API documentation but here it is  https://fastrash-1337.ew.r.appspot.com/api-docs

**Comment by Codeindeed** [comment]
Task is Done
