### ISSUE TITLE
Sign Up page 

### ISSUE THREAD

**Issue by Codeindeed** [dscfuto-org/fasthrash-FE#3]
Recreate the sign up page design

**Comment by Codeindeed** [comment]
Recreate the sign up form design with chakra UI form tag or react-router  form tag  message me if you meet a blocker

**Comment by Evangel2020** [comment]
Ok.
Thank you for the information.
When is the deadline??

**Comment by Codeindeed** [comment]
tommorow

**Comment by Codeindeed** [comment]
Done by @viceodev  so its closed
